services:
    db:
        image: postgres:18
        restart: always
        env_file: .env
        volumes:
            - pgdata:/var/lib/postgresql
            - ./init-db:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL","pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    api:
        build: .
        restart: always
        env_file: .env
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8000:8000"

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

volumes:
    pgdata: